-- Minimal, controlled config for the Hyprscheme test harness.
-- The harness sets XDG_CONFIG_HOME to this directory, so nothing from the
-- real user config leaks in. The scheme file is minimal; tests inject the
-- rest through hyprctl scheme.
hl.config({ autogenerated = true })
hl.bind("SUPER", "Q", function() hl.exec_cmd("foot") end)
