-- Minimal, controlled config for the Hyprscheme test harness.
-- The harness sets XDG_CONFIG_HOME to this directory, so nothing from the
-- real user config leaks in. This file is the irreducible compositor-side
-- bootstrap: hyprland's config language is lua, and the scheme plugin does
-- not exist until it is loaded, so this one line cannot be scheme. The
-- scheme config (hyprland.scm) owns everything else, including the test
-- binds.
hl.config({ autogenerated = true })
